# Workflow for converting xls crosswalks to json
### This script checks GitHub issues for submission of crosswalks (googlesheets) and runs the conversion if a new one has been submitted

name: CrossWalks xls to json conversion

on:
  issues:
    types: [opened, edited, milestoned]

#  schedule: 
#    - cron:  '* * * * *'

jobs: 
  run:
    runs-on: windows-latest
    env: 
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GSUITE_CREDENTIALS: ${{secrets.GSUITE_CREDENTIALS}}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python update_stuff.py
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "update data" -a
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        super_secret: ${{ secrets.CROSSWALKS_SECRET }}
        branch: main 
